// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF3PnOsNgsk20dnSr0ZiT7rVv2C77rMDE',
    appId: '1:1035184227155:web:37e3b97cfff72369aa17a6',
    messagingSenderId: '1035184227155',
    projectId: 'avatar-shoppingmall',
    authDomain: 'avatar-shoppingmall.firebaseapp.com',
    storageBucket: 'avatar-shoppingmall.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ZcmdraKJmLfFzXg_B7YwUPu9WEgQf0I',
    appId: '1:1035184227155:android:15d595c776927f31aa17a6',
    messagingSenderId: '1035184227155',
    projectId: 'avatar-shoppingmall',
    storageBucket: 'avatar-shoppingmall.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJjWr3FpVbEKcZEp-EuBssKVUlPRVV6gs',
    appId: '1:1035184227155:ios:64878f7e1d867d1daa17a6',
    messagingSenderId: '1035184227155',
    projectId: 'avatar-shoppingmall',
    storageBucket: 'avatar-shoppingmall.appspot.com',
    iosClientId:
        '1035184227155-b0har6psdlra3kul9ht92qj42omenjbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.avatar3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJjWr3FpVbEKcZEp-EuBssKVUlPRVV6gs',
    appId: '1:1035184227155:ios:64878f7e1d867d1daa17a6',
    messagingSenderId: '1035184227155',
    projectId: 'avatar-shoppingmall',
    storageBucket: 'avatar-shoppingmall.appspot.com',
    iosClientId:
        '1035184227155-b0har6psdlra3kul9ht92qj42omenjbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.avatar3',
  );
}
